logging:
  level: INFO

  appenders:
    - type: console
      threshold: ALL
      timeZone: IST

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    port: 8080
    type: http

mongoHost : localhost
mongoPort : 27017
mongoDB : books
collectionName: books